name: Deploy Supabase Edge Functions

on:
  push:
    branches: [main]

jobs:
  deploy-functions:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Supabase CLI (unofficial)
        run: |
          rm -f supabase
          curl -sL https://github.com/supabase/cli/releases/download/v1.0.0/supabase_1.0.0_linux_amd64.tar.gz | tar xz
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

      - name: Deploy Edge Function
        run: |
          supabase functions deploy generate-image --project-ref $SUPABASE_PROJECT_ID
